### ISSUE TITLE
Add LICENSE.md to repository

### ISSUE THREAD

**Issue by oscarhermoso** [carstenlebek/svelte-email#10]
Awesome project, just wondering whether it needs a license file?

`react-email` is published under the MIT license, I assume intention is the same or similar for `svelte-email`?

**Comment by brinehart** [comment]
2nd this. I'd love to use this for a project I might be working on soon but need to know what license it is under first.

**Comment by carstenlebek** [comment]
Sorry, forgot to add it when I've published it. Added the MIT license.
